services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: medibot-redis
    ports:
      - "6379:6379"   # Redis Port
      - "8001:8001"   # Redis Insight (GUI)
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: